export const tagTypes = {
  user: "User",
  users: "Users",
  terms: "Terms",
  earning: "Earning",
  overview: "Overview",
  notification: "Notification",
  vendor: "Vendor",
  vendorRequest: "VendorRequest",
  serviceType: "ServiceType",
  service: "Service",
  serviceRequest: "ServiceRequest",
  trsnsaction: "TransAction",
  admin: "Admin",
  refund: "Refund",
  feedback: "Feedack",
  payout: "Payouts",
  support: "Support",
  notificationPost: "NotificationPost",
  notificationAction: "NotificationAction",
  banner: "Banner",
};

export const tagTypesList = [
  tagTypes.user,
  tagTypes.users,
  tagTypes.terms,
  tagTypes.earning,
  tagTypes.overview,
  tagTypes.notification,
  tagTypes.vendor,
  tagTypes.service,
  tagTypes.serviceType,
  tagTypes.serviceRequest,
  tagTypes.trsnsaction,
  tagTypes.admin,
  tagTypes.refund,
  tagTypes.feedback,
  tagTypes.payout,
  tagTypes.support,
  tagTypes.notificationPost,
  tagTypes.notificationAction,
  tagTypes.banner,
  tagTypes.vendorRequest
];
